services:
  portainer:
    image: portainer/portainer-ce:2.33.3-alpine@sha256:cbe5bf17ee906793c700440dcf8e1358d4fdd1a7eb64b4f276af9cf9a23935d1  # version 2.33.3-alpine (was latest)
    container_name: portainer
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      # --- HTTPS-Router ---
      - "traefik.http.routers.portainer.rule=Host(`portainer.home`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"

      # interne Weiterleitung
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

      # Traefik-Netz explizit setzen
      - "traefik.docker.network=proxy"

volumes:
  portainer_data:

networks:
  proxy:
    external: true
