volumes:
  etc_wireguard:
  wireguard_ui_db:
    external: true
    name: homeserver_wireguard_ui_db

services:
  wireguard:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      SESSION_SECRET: ${WIREGUARD_UI_SESSION_SECRET:-change-me}
      WGUI_USERNAME: ${WIREGUARD_UI_USERNAME:-admin}
      WGUI_PASSWORD: ${WIREGUARD_UI_PASSWORD:-admin}
      WGUI_MANAGE_START: "true"
      WGUI_MANAGE_RESTART: "true"
      BIND_ADDRESS: 0.0.0.0:5000
    volumes:
      - wireguard_ui_db:/app/db
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
    networks:
      wg:
        ipv4_address: 10.42.42.42
      proxy: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`wg.home`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls=true"
      - "traefik.http.services.wireguard.loadbalancer.server.port=5000"
      - "traefik.http.routers.wireguard-http.rule=Host(`wg.home`)"
      - "traefik.http.routers.wireguard-http.entrypoints=web"
      - "traefik.http.routers.wireguard-http.middlewares=wireguard-redirect"
      - "traefik.http.middlewares.wireguard-redirect.redirectscheme.scheme=https"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  wg:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
  proxy:
    external: true
    name: proxy
