version: "3.9"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    restart: unless-stopped

    env_file:
      - .env

    environment:
      WEBUI_SECRET_KEY: "${OWUI_SECRET_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

      ENABLE_CORS: "true"

      OAUTH_PROVIDER_NAME: "authentik"
      OAUTH_CLIENT_ID: "${OWUI_OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OWUI_OAUTH_CLIENT_SECRET}"
      OPENID_PROVIDER_URL: "https://authentik.home/application/o/openweb/.well-known/openid-configuration"
      OPENID_REDIRECT_URI: "https://ai.home/oauth/oidc/callback"
      WEBUI_URL: "https://ai.home"
      ENABLE_OAUTH_SIGNUP: "true"
      ENABLE_LOGIN_FORM: "false"
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
      SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"

    volumes:
      # system trust store
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      # OpenWebUI persistent data
      - ./internals/openwebui/data:/app/backend/data

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`ai.home`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.tls=true"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

    networks:
      - proxy

networks:
  proxy:
    external: true
