services:
  portainer:
    image: portainer/portainer-ce:latest  # fresh DB, latest release
    container_name: portainer
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./internals/portainer:/data

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      # --- HTTPS-Router ---
      - "traefik.http.routers.portainer.rule=Host(`portainer.home`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"

      # interne Weiterleitung
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

      # Traefik-Netz explizit setzen
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
